"""
Water Valuation Module for Stage 8 Techno-Economic Analysis.

Calculates the economic value generated by recovering and reusing treated permeate water,
accounting for both avoided freshwater utility purchases and avoided wastewater sewer discharge fees.
"""

from typing import Dict
from dataclasses import dataclass
from economics.cost_config import EconomicConfig


@dataclass
class WaterValueResult:
    permeate_volume_m3: float
    avoided_freshwater_value_kes: float
    avoided_discharge_value_kes: float
    total_water_value_kes: float
    effective_value_per_m3_kes: float


def calculate_water_value(
    permeate_volume_m3: float,
    config: EconomicConfig,
) -> WaterValueResult:
    """
    Compute the gross monetary value of recycled RO permeate water.
    
    V_water = Q_reused * (C_freshwater + C_discharge_avoided)
    """
    vol = max(0.0, float(permeate_volume_m3))
    freshwater_val = vol * config.water_purchase_cost_kes_m3
    discharge_val = vol * config.wastewater_discharge_cost_kes_m3
    total_val = freshwater_val + discharge_val
    unit_val = (total_val / vol) if vol > 0 else (config.water_purchase_cost_kes_m3 + config.wastewater_discharge_cost_kes_m3)

    return WaterValueResult(
        permeate_volume_m3=vol,
        avoided_freshwater_value_kes=freshwater_val,
        avoided_discharge_value_kes=discharge_val,
        total_water_value_kes=total_val,
        effective_value_per_m3_kes=unit_val,
    )
